### ISSUE TITLE
Activity iamutkarshtiwari.github.io.ananas.editimage.EditImageActivity has leaked window

### ISSUE THREAD

**Issue by hermannkuschke** [iamutkarshtiwari/Ananas#1]
Hi! First of all, thank you for this very handy tool!

I just want to report that I get the above mentioned exception when using more than one of the editing tools. I will also look into it on my side and report back, but wanted you to know.

The crash log is as follows:

`android.view.WindowLeaked: Activity iamutkarshtiwari.github.io.ananas.editimage.EditImageActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{12dc24ab V.E..... R......D 0,0-480,174} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:530)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:287)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
        at android.app.Dialog.show(Dialog.java:325)
        at iamutkarshtiwari.github.io.ananas.editimage.fragment.FilterListFragment$ProcessingImage.onPreExecute(FilterListFragment.java:172)
        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:591)
        at android.os.AsyncTask.execute(AsyncTask.java:539)
        at iamutkarshtiwari.github.io.ananas.editimage.fragment.FilterListFragment.enableFilter(FilterListFragment.java:121)
        at iamutkarshtiwari.github.io.ananas.editimage.adapter.FilterAdapter$1.onClick(FilterAdapter.java:78)
        at android.view.View.performClick(View.java:5246)
        at android.view.View$PerformClick.run(View.java:21256)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6934)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`

This happened when I tried to apply a filter. When tapping on the appropriate filter, the app crashes with this message. This also seems to happen when going to the "Beauty" tool and trying to apply anything in there.

Thank you.

Regards,
Hermann

**Comment by iamutkarshtiwari** [comment]
Looking into this.

**Comment by iamutkarshtiwari** [comment]
@hermannkuschke Please try the new version: [1.1.0](https://github.com/iamutkarshtiwari/Ananas/releases/tag/1.1.0)

**Comment by iamutkarshtiwari** [comment]
Should be fixed in release `1.1.2` with [this commit](https://github.com/iamutkarshtiwari/Ananas/commit/57b6cdb84b2cf2878b4bf7e7ba102cd86860a62e)

**Comment by iamutkarshtiwari** [comment]
Fixed in [`v1.1.1`](https://github.com/iamutkarshtiwari/Ananas/releases/tag/1.1.1)
