### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by adityapandey9** [iamutkarshtiwari/Ananas#53]
java.lang.NullPointerException: Attempt to write to field 'int iamutkarshtiwari.github.io.ananas.editimage.EditImageActivity.mode' on a null object reference
	at iamutkarshtiwari.github.io.ananas.editimage.fragment.StickerFragment.onShow(StickerFragment.java:104)
	at iamutkarshtiwari.github.io.ananas.editimage.fragment.MainMenuFragment.onStickClick(MainMenuFragment.java:145)
	at iamutkarshtiwari.github.io.ananas.editimage.fragment.MainMenuFragment.onClick(MainMenuFragment.java:123)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25885)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:132)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:126)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:42)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:75)
	at androidx.test.espresso.action.Tap.b(Tap.java:16)
	at androidx.test.espresso.action.Tap$1.a(Tap.java:2)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:33)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

When I was testing it on Pixel 2, API level 28.

**Comment by iamutkarshtiwari** [comment]
@adityapandey9 Could you share the reproduction steps?

**Comment by adityapandey9** [comment]
@iamutkarshtiwari I have fixed that locally, It is working fine on my side.
