### ISSUE TITLE
Canvas: trying to draw too large(115200000bytes) bitmap.

### ISSUE THREAD

**Issue by trungnnq** [iamutkarshtiwari/Ananas#96]
Hello sir!
When I try to load a big image from storage (~9MB), this crash happen
Fatal Exception: java.lang.RuntimeException
Canvas: trying to draw too large(115200000bytes) bitmap.

```

Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(115200000bytes) bitmap.
       at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:283)
       at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:69)
       at iamutkarshtiwari.github.io.ananas.editimage.view.imagezoom.graphic.FastBitmapDrawable.draw(FastBitmapDrawable.java:37)
       at android.widget.ImageView.onDraw(ImageView.java:1436)
       at android.view.View.draw(View.java:22406)
       at android.view.View.updateDisplayListIfDirty(View.java:21282)
       at android.view.View.draw(View.java:22137)
      
```
Could you support me fix it?

**Comment by trungnnq** [comment]
Libs ver: 1.2.6
Android: 9 - API 28
